//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class QuestionData
{
	public int qu_id;
	public int qu_cat_id;
	public int qu_sec_cat_id;
	public int qu_th_cat_id;
	public string qu_text;
	public string qu_difficulty;
	public string qu_option1;
	public string qu_option2;
	public string qu_option3;
	public string qu_option4;
	public int qu_answer;
	public string qu_status;
	public DateTime qu_created_on;
	
}
