//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class CatagoryData
{
	public int category_id;
	public int restaurant_user_id;
	public string category_name;
	public string category_image;
	public DateTime category_created_on;
	public string category_status;
}